[app]
host = "0.0.0.0"
port = 18081

[database]
host = "127.0.0.1"
name = "rust_admin"
user = "root"
password = "123456"
port = 3306

[oss]
access_key_id = ""
access_key_secret = ""
region = ""
end_point = ""
bucket = ""